from __future__ import annotations

import json
import re
import shutil
from pathlib import Path
from typing import Any

from .core.graph import add_edge, add_node
from .core.io import read_json as core_read_json
from .discovery import AnnotationError
from .memory import ContextBroker, reindex_workspace
from .sources import mark_source_processed
from .workspace import read_json, state_path, update_state, utc_now, workspace_path

DECISION_RISKS = {"low", "med", "medium", "high"}
REVERSIBILITY_VALUES = {"easy", "moderate", "hard-to-reverse", "irreversible"}
GROUNDING_GLOBS = (
    "01_discovery/**/*.md",
    "02_requirements/**/*.md",
    "03_specs/**/*.md",
    "04_backlog/**/*.md",
    "05_quality/**/*.md",
    "06_traceability/**/*.md",
    "08_context_packs/**/*.md",
)


def load_decision_source(source: Path, *, label: str) -> dict[str, Any]:
    try:
        data = core_read_json(source, {})
    except json.JSONDecodeError as exc:
        raise AnnotationError(f"Invalid JSON in {label}: {exc}") from exc
    if not isinstance(data, dict):
        raise AnnotationError(f"{label} must be a JSON object.")
    return data


def validate_cited_decisions(data: dict[str, Any], grounding_text: str, *, label: str) -> list[dict[str, str]]:
    raw = data.get("decisions", [])
    if raw is None:
        raw = []
    if not isinstance(raw, list):
        raise AnnotationError(f"{label} decisions must be a list.")
    decisions: list[dict[str, str]] = []
    for item in raw:
        if not isinstance(item, dict):
            raise AnnotationError(f"Each {label} decision must be an object.")
        decision_id = str(item.get("id", "")).strip().upper()
        if not re.match(r"^DEC-[A-Z0-9-]+$", decision_id):
            raise AnnotationError(f"{decision_id or '<missing>'}: decision id must start with DEC-.")
        title = str(item.get("title", "")).strip() or decision_id
        decision = str(item.get("decision", "")).strip()
        if not decision:
            raise AnnotationError(f"{decision_id}: decision text is required.")
        lens = str(item.get("lens", "product")).strip().lower() or "product"
        risk = str(item.get("risk", "")).strip().lower()
        if risk not in DECISION_RISKS:
            raise AnnotationError(f"{decision_id}: risk must be one of {', '.join(sorted(DECISION_RISKS))}.")
        reversibility = str(item.get("reversibility", "")).strip().lower()
        if reversibility not in REVERSIBILITY_VALUES:
            raise AnnotationError(
                f"{decision_id}: reversibility must be one of {', '.join(sorted(REVERSIBILITY_VALUES))}."
            )
        evidence = str(item.get("evidence", "")).strip()
        if not evidence:
            raise AnnotationError(f"{decision_id}: evidence is required.")
        if evidence not in grounding_text:
            raise AnnotationError(f"{decision_id}: evidence quote is not found verbatim in local workspace evidence.")
        consequence = str(item.get("consequence", "")).strip()
        decisions.append(
            {
                "id": decision_id,
                "title": title,
                "lens": lens,
                "risk": "med" if risk == "medium" else risk,
                "reversibility": reversibility,
                "decision": decision,
                "evidence": evidence,
                "consequence": consequence,
            }
        )
    return decisions


def workspace_grounding_text(base: Path) -> str:
    paths: list[Path] = []
    seen: set[str] = set()
    for pattern in GROUNDING_GLOBS:
        for path in sorted(base.glob(pattern)):
            if not path.is_file():
                continue
            key = str(path.resolve()).lower()
            if key in seen:
                continue
            seen.add(key)
            paths.append(path)
    chunks: list[str] = []
    for path in paths:
        try:
            chunks.append(path.read_text(encoding="utf-8"))
        except OSError:
            continue
    return "\n\n".join(chunks)


def render_decision_register(project_id: str, decisions: list[dict[str, str]]) -> str:
    blocks = []
    for item in decisions:
        blocks.append(
            f"""## {item['id']} - {item['title']}

- Lens: `{item['lens']}`
- Risk: `{item['risk']}`
- Reversibility: `{item['reversibility']}`
- Status: `pending_review`
- Evidence: {item['evidence']}

Decision:

{item['decision']}

Consequence:

{item['consequence'] or 'TBD'}
"""
        )
    body = "\n".join(blocks) or "_No hard-to-reverse decisions registered._\n"
    return f"""# Hard-To-Reverse Decision Register - {project_id}

This register is generated by `/self-review`. It records decisions that deserve BA/Product review before downstream agents treat them as stable execution facts.

{body}
"""


def register_gate_override(
    project_id: str,
    gate: str,
    source: Path,
    *,
    verdict: str,
    findings: list[str],
) -> dict[str, object]:
    base = workspace_path(project_id)
    if verdict in {"PASS", "VALID"} and not findings:
        raise RuntimeError(f"/{gate} has no failing or warning gate state to override.")
    data = load_decision_source(source, label=f"{gate} override source")
    decisions = validate_cited_decisions(data, workspace_grounding_text(base), label=f"{gate} override")
    if not decisions:
        raise AnnotationError(f"{gate} override source must declare at least one decision.")

    override_dir = base / "06_traceability" / "gate_overrides"
    override_dir.mkdir(parents=True, exist_ok=True)
    stored_source = unique_path(override_dir / f"{gate}-{source.stem}.json")
    shutil.copyfile(source, stored_source)
    report_path = unique_path(override_dir / f"{gate}-override-report.md")
    timestamp = utc_now()

    report_path.write_text(
        render_gate_override_report(project_id, gate, source.stem, verdict, findings, decisions, timestamp),
        encoding="utf-8",
    )

    state = read_json(state_path(project_id), {})
    existing_entries = state.get("gate_override_decisions", [])
    register_entries = list(existing_entries) if isinstance(existing_entries, list) else []
    new_entries = [
        {
            "gate": gate,
            "verdict": verdict,
            "recorded_at": timestamp,
            "source": stored_source.relative_to(base).as_posix(),
            "findings": [str(item) for item in findings],
            **decision,
        }
        for decision in decisions
    ]
    register_entries.extend(new_entries)

    register_path = override_dir / "decision_register.md"
    register_path.write_text(render_gate_override_register(project_id, register_entries), encoding="utf-8")

    report_id = add_node(
        project_id,
        "DEC",
        "gate_override_report",
        report_path,
        f"{gate} override rationale: {source.stem}",
        status="accepted",
        domain="governance",
    )
    decision_ids: list[str] = []
    for decision in decisions:
        decision_id = add_node(
            project_id,
            "DEC",
            "hard_to_reverse_decision",
            register_path,
            decision["title"],
            status="accepted",
            domain=decision["lens"],
        )
        decision_ids.append(decision_id)
        add_edge(project_id, report_id, decision_id, "records_decision")

    broker = ContextBroker(project_id)
    broker.index_artifact(
        report_id,
        "gate_override_report",
        report_path,
        report_path.read_text(encoding="utf-8"),
        domain="governance",
        trace_ids=[report_id, *decision_ids],
    )
    broker.index_artifact(
        "GATE-OVERRIDE-DECISIONS",
        "decision_register",
        register_path,
        register_path.read_text(encoding="utf-8"),
        domain="governance",
        trace_ids=[report_id, *decision_ids],
    )
    reindex_workspace(project_id)
    mark_source_processed(project_id, source, "gate_override_applied", report_id)
    mark_source_processed(project_id, report_path, "gate_override_report", report_id)
    mark_source_processed(project_id, register_path, "gate_override_decision_register", report_id)
    update_state(project_id, gate_override_decisions=register_entries, last_gate_override_id=report_id)
    return {
        "gate": gate,
        "verdict": verdict,
        "recorded_at": timestamp,
        "report": str(report_path.as_posix()),
        "decision_register": str(register_path.as_posix()),
        "stored_source": str(stored_source.as_posix()),
        "decisions": [item["id"] for item in decisions],
        "decision_node_ids": decision_ids,
        "findings": [str(item) for item in findings],
    }


def render_gate_override_report(
    project_id: str,
    gate: str,
    label: str,
    verdict: str,
    findings: list[str],
    decisions: list[dict[str, str]],
    timestamp: str,
) -> str:
    findings_block = "\n".join(f"- {item}" for item in findings) or "- No explicit gate findings were captured."
    decision_rows = "\n".join(
        f"| `{item['id']}` | {item['risk']} | {item['reversibility']} | {item['decision']} | {item['evidence']} |"
        for item in decisions
    )
    return f"""# Gate Override Report - {project_id}

- Gate: `/{gate}`
- Recorded at: `{timestamp}`
- Source: `{label}`
- Underlying verdict: `{verdict}`

This report records a cited human rationale for proceeding despite the gate result. It does not rewrite the underlying gate verdict.

## Gate Findings Snapshot

{findings_block}

## Override Decisions

| Decision ID | Risk | Reversibility | Decision | Evidence Cited |
| --- | --- | --- | --- | --- |
{decision_rows}
"""


def render_gate_override_register(project_id: str, entries: list[dict[str, Any]]) -> str:
    blocks: list[str] = []
    for item in entries:
        findings = "\n".join(f"  - {value}" for value in item.get("findings", [])) or "  - No findings recorded."
        blocks.append(
            f"""## {item['id']} - {item['title']}

- Gate: `/{item.get('gate', 'unknown')}`
- Recorded at: `{item.get('recorded_at', 'unknown')}`
- Underlying verdict: `{item.get('verdict', 'unknown')}`
- Lens: `{item.get('lens', 'product')}`
- Risk: `{item.get('risk', 'med')}`
- Reversibility: `{item.get('reversibility', 'moderate')}`
- Evidence: {item.get('evidence', '')}
- Source: `{item.get('source', '')}`

Decision:

{item.get('decision', '')}

Consequence:

{item.get('consequence', '') or 'TBD'}

Findings snapshot:
{findings}
"""
        )
    body = "\n".join(blocks) or "_No gate overrides recorded._\n"
    return f"""# Gate Override Decision Register - {project_id}

This register records cited human rationales used to proceed despite a gate verdict. The underlying gate verdicts stay visible; this artifact only records the human override rationale.

{body}
"""


def unique_path(path: Path) -> Path:
    if not path.exists():
        return path
    stem, suffix = path.stem, path.suffix
    for index in range(2, 1000):
        candidate = path.with_name(f"{stem}-{index}{suffix}")
        if not candidate.exists():
            return candidate
    raise RuntimeError(f"Cannot create unique path for {path}")
